version: "3"
services:
    tightrope:
        image: bennybitcoin/tightrope:1
        container_name: tightrope
        volumes:
          - ./config/local.json:/tightrope/config/local.json
        network_mode: "host"
